### ISSUE TITLE
Big thanks for your challenge3 source code - it was very helpful! I can't solve it for two days and only your code is cleared the sky =)

### ISSUE THREAD

**Issue by VladimirMoor** [shiftingsand/100DaysofSwiftUI-Day52-CupcakeCorner#1]

**Comment by VladimirMoor** [comment]
And finally I can see how to use classes and structs for data models =)

**Comment by shiftingsand** [comment]
Glad that it helped you! I was completely stuck on the Guess The Flag challenge and looking at code from other people helped me understand how SwiftUI works.
